/**
 * Datos de Provincias, Localidades y Barrios de Argentina
 * Fuente: Basado en datos de GeoRef API y divisiones administrativas
 * Actualizado: 2024
 */

export interface Provincia {
    id: string;
    nombre: string;
  }
  
  export interface Localidad {
    id: string;
    nombre: string;
    provinciaId: string;
  }
  
  export interface Barrio {
    id: string;
    nombre: string;
    localidadId: string;
  }
  
  export const PROVINCIAS: Provincia[] = [
    { id: '02', nombre: 'Ciudad Autónoma de Buenos Aires' },
    { id: '06', nombre: 'Buenos Aires' },
    { id: '10', nombre: 'Catamarca' },
    { id: '14', nombre: 'Córdoba' },
    { id: '18', nombre: 'Corrientes' },
    { id: '22', nombre: 'Chaco' },
    { id: '26', nombre: 'Chubut' },
    { id: '30', nombre: 'Entre Ríos' },
    { id: '34', nombre: 'Formosa' },
    { id: '38', nombre: 'Jujuy' },
    { id: '42', nombre: 'La Pampa' },
    { id: '46', nombre: 'La Rioja' },
    { id: '50', nombre: 'Mendoza' },
    { id: '54', nombre: 'Misiones' },
    { id: '58', nombre: 'Neuquén' },
    { id: '62', nombre: 'Río Negro' },
    { id: '66', nombre: 'Salta' },
    { id: '70', nombre: 'San Juan' },
    { id: '74', nombre: 'San Luis' },
    { id: '78', nombre: 'Santa Cruz' },
    { id: '82', nombre: 'Santa Fe' },
    { id: '86', nombre: 'Santiago del Estero' },
    { id: '90', nombre: 'Tucumán' },
    { id: '94', nombre: 'Tierra del Fuego' },
  ];
  
  // Localidades principales por provincia
  export const LOCALIDADES: Record<string, Localidad[]> = {
    // Ciudad Autónoma de Buenos Aires (barrios como localidades)
    '02': [
      { id: '02-001', nombre: 'Agronomía', provinciaId: '02' },
      { id: '02-002', nombre: 'Almagro', provinciaId: '02' },
      { id: '02-003', nombre: 'Balvanera', provinciaId: '02' },
      { id: '02-004', nombre: 'Barracas', provinciaId: '02' },
      { id: '02-005', nombre: 'Belgrano', provinciaId: '02' },
      { id: '02-006', nombre: 'Boedo', provinciaId: '02' },
      { id: '02-007', nombre: 'Caballito', provinciaId: '02' },
      { id: '02-008', nombre: 'Chacarita', provinciaId: '02' },
      { id: '02-009', nombre: 'Coghlan', provinciaId: '02' },
      { id: '02-010', nombre: 'Colegiales', provinciaId: '02' },
      { id: '02-011', nombre: 'Constitución', provinciaId: '02' },
      { id: '02-012', nombre: 'Flores', provinciaId: '02' },
      { id: '02-013', nombre: 'Floresta', provinciaId: '02' },
      { id: '02-014', nombre: 'La Boca', provinciaId: '02' },
      { id: '02-015', nombre: 'La Paternal', provinciaId: '02' },
      { id: '02-016', nombre: 'Liniers', provinciaId: '02' },
      { id: '02-017', nombre: 'Mataderos', provinciaId: '02' },
      { id: '02-018', nombre: 'Monte Castro', provinciaId: '02' },
      { id: '02-019', nombre: 'Montserrat', provinciaId: '02' },
      { id: '02-020', nombre: 'Nueva Pompeya', provinciaId: '02' },
      { id: '02-021', nombre: 'Núñez', provinciaId: '02' },
      { id: '02-022', nombre: 'Palermo', provinciaId: '02' },
      { id: '02-023', nombre: 'Parque Avellaneda', provinciaId: '02' },
      { id: '02-024', nombre: 'Parque Chacabuco', provinciaId: '02' },
      { id: '02-025', nombre: 'Parque Chas', provinciaId: '02' },
      { id: '02-026', nombre: 'Parque Patricios', provinciaId: '02' },
      { id: '02-027', nombre: 'Puerto Madero', provinciaId: '02' },
      { id: '02-028', nombre: 'Recoleta', provinciaId: '02' },
      { id: '02-029', nombre: 'Retiro', provinciaId: '02' },
      { id: '02-030', nombre: 'Saavedra', provinciaId: '02' },
      { id: '02-031', nombre: 'San Cristóbal', provinciaId: '02' },
      { id: '02-032', nombre: 'San Nicolás', provinciaId: '02' },
      { id: '02-033', nombre: 'San Telmo', provinciaId: '02' },
      { id: '02-034', nombre: 'Vélez Sársfield', provinciaId: '02' },
      { id: '02-035', nombre: 'Versalles', provinciaId: '02' },
      { id: '02-036', nombre: 'Villa Crespo', provinciaId: '02' },
      { id: '02-037', nombre: 'Villa del Parque', provinciaId: '02' },
      { id: '02-038', nombre: 'Villa Devoto', provinciaId: '02' },
      { id: '02-039', nombre: 'Villa General Mitre', provinciaId: '02' },
      { id: '02-040', nombre: 'Villa Lugano', provinciaId: '02' },
      { id: '02-041', nombre: 'Villa Luro', provinciaId: '02' },
      { id: '02-042', nombre: 'Villa Ortúzar', provinciaId: '02' },
      { id: '02-043', nombre: 'Villa Pueyrredón', provinciaId: '02' },
      { id: '02-044', nombre: 'Villa Real', provinciaId: '02' },
      { id: '02-045', nombre: 'Villa Riachuelo', provinciaId: '02' },
      { id: '02-046', nombre: 'Villa Santa Rita', provinciaId: '02' },
      { id: '02-047', nombre: 'Villa Soldati', provinciaId: '02' },
      { id: '02-048', nombre: 'Villa Urquiza', provinciaId: '02' },
    ],
    
    // Buenos Aires (localidades del Gran Buenos Aires y resto de la provincia)
    '06': [
      // Partidos del GBA
      { id: '06-001', nombre: 'La Plata', provinciaId: '06' },
      { id: '06-002', nombre: 'Mar del Plata', provinciaId: '06' },
      { id: '06-003', nombre: 'Bahía Blanca', provinciaId: '06' },
      { id: '06-004', nombre: 'San Isidro', provinciaId: '06' },
      { id: '06-005', nombre: 'Quilmes', provinciaId: '06' },
      { id: '06-006', nombre: 'Lanús', provinciaId: '06' },
      { id: '06-007', nombre: 'Avellaneda', provinciaId: '06' },
      { id: '06-008', nombre: 'Lomas de Zamora', provinciaId: '06' },
      { id: '06-009', nombre: 'San Martín', provinciaId: '06' },
      { id: '06-010', nombre: 'Tigre', provinciaId: '06' },
      { id: '06-011', nombre: 'Vicente López', provinciaId: '06' },
      { id: '06-012', nombre: 'Morón', provinciaId: '06' },
      { id: '06-013', nombre: 'Tres de Febrero', provinciaId: '06' },
      { id: '06-014', nombre: 'San Miguel', provinciaId: '06' },
      { id: '06-015', nombre: 'Pilar', provinciaId: '06' },
      { id: '06-016', nombre: 'Escobar', provinciaId: '06' },
      { id: '06-017', nombre: 'Campana', provinciaId: '06' },
      { id: '06-018', nombre: 'Zárate', provinciaId: '06' },
      { id: '06-019', nombre: 'Luján', provinciaId: '06' },
      { id: '06-020', nombre: 'Mercedes', provinciaId: '06' },
      { id: '06-021', nombre: 'Tandil', provinciaId: '06' },
      { id: '06-022', nombre: 'Olavarría', provinciaId: '06' },
      { id: '06-023', nombre: 'Azul', provinciaId: '06' },
      { id: '06-024', nombre: 'Necochea', provinciaId: '06' },
      { id: '06-025', nombre: 'Pergamino', provinciaId: '06' },
      { id: '06-026', nombre: 'Junín', provinciaId: '06' },
      { id: '06-027', nombre: 'Chivilcoy', provinciaId: '06' },
      { id: '06-028', nombre: 'Berazategui', provinciaId: '06' },
      { id: '06-029', nombre: 'Florencio Varela', provinciaId: '06' },
      { id: '06-030', nombre: 'San Fernando', provinciaId: '06' },
      { id: '06-031', nombre: 'Ituzaingó', provinciaId: '06' },
      { id: '06-032', nombre: 'Merlo', provinciaId: '06' },
      { id: '06-033', nombre: 'Moreno', provinciaId: '06' },
      { id: '06-034', nombre: 'José C. Paz', provinciaId: '06' },
      { id: '06-035', nombre: 'Malvinas Argentinas', provinciaId: '06' },
      { id: '06-036', nombre: 'Hurlingham', provinciaId: '06' },
      { id: '06-037', nombre: 'San Nicolás', provinciaId: '06' },
      { id: '06-038', nombre: 'Bragado', provinciaId: '06' },
      { id: '06-039', nombre: 'Chacabuco', provinciaId: '06' },
      { id: '06-040', nombre: 'Bolívar', provinciaId: '06' },
      { id: '06-041', nombre: 'Balcarce', provinciaId: '06' },
      { id: '06-042', nombre: 'Benito Juárez', provinciaId: '06' },
      { id: '06-043', nombre: 'Chascomús', provinciaId: '06' },
      { id: '06-044', nombre: 'Dolores', provinciaId: '06' },
      { id: '06-045', nombre: 'General Madariaga', provinciaId: '06' },
      { id: '06-046', nombre: 'Lobos', provinciaId: '06' },
      { id: '06-047', nombre: 'Monte', provinciaId: '06' },
      { id: '06-048', nombre: 'Navarro', provinciaId: '06' },
      { id: '06-049', nombre: 'Roque Pérez', provinciaId: '06' },
      { id: '06-050', nombre: 'Saladillo', provinciaId: '06' },
      { id: '06-051', nombre: 'San Vicente', provinciaId: '06' },
      { id: '06-052', nombre: 'Presidente Perón', provinciaId: '06' },
      { id: '06-053', nombre: 'Esteban Echeverría', provinciaId: '06' },
      { id: '06-054', nombre: 'Almirante Brown', provinciaId: '06' },
      { id: '06-055', nombre: 'Ezeiza', provinciaId: '06' },
      { id: '06-056', nombre: 'General Rodríguez', provinciaId: '06' },
      { id: '06-057', nombre: 'Marcos Paz', provinciaId: '06' },
      { id: '06-058', nombre: 'General Las Heras', provinciaId: '06' },
      { id: '06-059', nombre: 'San Antonio de Areco', provinciaId: '06' },
      { id: '06-060', nombre: 'Carmen de Areco', provinciaId: '06' },
      { id: '06-061', nombre: 'Capitán Sarmiento', provinciaId: '06' },
      { id: '06-062', nombre: 'Colón', provinciaId: '06' },
      { id: '06-063', nombre: 'Rojas', provinciaId: '06' },
      { id: '06-064', nombre: 'Salto', provinciaId: '06' },
      { id: '06-065', nombre: 'Lincoln', provinciaId: '06' },
      { id: '06-066', nombre: '9 de Julio', provinciaId: '06' },
      { id: '06-067', nombre: 'Carlos Casares', provinciaId: '06' },
      { id: '06-068', nombre: 'Pehuajó', provinciaId: '06' },
      { id: '06-069', nombre: 'Trenque Lauquen', provinciaId: '06' },
      { id: '06-070', nombre: 'General Villegas', provinciaId: '06' },
      { id: '06-071', nombre: 'Tres Arroyos', provinciaId: '06' },
      { id: '06-072', nombre: 'Coronel Dorrego', provinciaId: '06' },
      { id: '06-073', nombre: 'Coronel Pringles', provinciaId: '06' },
      { id: '06-074', nombre: 'Pigüé', provinciaId: '06' },
      { id: '06-075', nombre: 'Tornquist', provinciaId: '06' },
      { id: '06-076', nombre: 'Punta Alta', provinciaId: '06' },
      { id: '06-077', nombre: 'Coronel Suárez', provinciaId: '06' },
      { id: '06-078', nombre: 'Laprida', provinciaId: '06' },
      { id: '06-079', nombre: 'Rauch', provinciaId: '06' },
      { id: '06-080', nombre: 'Ayacucho', provinciaId: '06' },
      
      // Más localidades importantes
      { id: '06-081', nombre: 'Alberti', provinciaId: '06' },
      { id: '06-082', nombre: 'Adrogué', provinciaId: '06' },
      { id: '06-083', nombre: 'Banfield', provinciaId: '06' },
      { id: '06-084', nombre: 'Beccar', provinciaId: '06' },
      { id: '06-085', nombre: 'Boulogne', provinciaId: '06' },
      { id: '06-086', nombre: 'Burzaco', provinciaId: '06' },
      { id: '06-087', nombre: 'Carapachay', provinciaId: '06' },
      { id: '06-088', nombre: 'Caseros', provinciaId: '06' },
      { id: '06-089', nombre: 'Castelar', provinciaId: '06' },
      { id: '06-090', nombre: 'Ciudad Evita', provinciaId: '06' },
      { id: '06-091', nombre: 'Ciudad Madero', provinciaId: '06' },
      { id: '06-092', nombre: 'Claypole', provinciaId: '06' },
      { id: '06-093', nombre: 'Don Torcuato', provinciaId: '06' },
      { id: '06-094', nombre: 'El Palomar', provinciaId: '06' },
      { id: '06-095', nombre: 'Gerli', provinciaId: '06' },
      { id: '06-096', nombre: 'Glew', provinciaId: '06' },
      { id: '06-097', nombre: 'Grand Bourg', provinciaId: '06' },
      { id: '06-098', nombre: 'Gregorio de Laferrère', provinciaId: '06' },
      { id: '06-099', nombre: 'Guernica', provinciaId: '06' },
      { id: '06-100', nombre: 'Haedo', provinciaId: '06' },
      { id: '06-101', nombre: 'Ingeniero Maschwitz', provinciaId: '06' },
      { id: '06-102', nombre: 'Isidro Casanova', provinciaId: '06' },
      { id: '06-103', nombre: 'Ituzaingó', provinciaId: '06' },
      { id: '06-104', nombre: 'José Mármol', provinciaId: '06' },
      { id: '06-105', nombre: 'Longchamps', provinciaId: '06' },
      { id: '06-106', nombre: 'Luis Guillón', provinciaId: '06' },
      { id: '06-107', nombre: 'Martínez', provinciaId: '06' },
      { id: '06-108', nombre: 'Monte Grande', provinciaId: '06' },
      { id: '06-109', nombre: 'Muñiz', provinciaId: '06' },
      { id: '06-110', nombre: 'Olivos', provinciaId: '06' },
      { id: '06-111', nombre: 'Pablo Nogués', provinciaId: '06' },
      { id: '06-112', nombre: 'Parque San Martín', provinciaId: '06' },
      { id: '06-113', nombre: 'Rafael Calzada', provinciaId: '06' },
      { id: '06-114', nombre: 'Rafael Castillo', provinciaId: '06' },
      { id: '06-115', nombre: 'Ramos Mejía', provinciaId: '06' },
      { id: '06-116', nombre: 'San Justo', provinciaId: '06' },
      { id: '06-117', nombre: 'San Martín', provinciaId: '06' },
      { id: '06-118', nombre: 'Santos Lugares', provinciaId: '06' },
      { id: '06-119', nombre: 'Tapiales', provinciaId: '06' },
      { id: '06-120', nombre: 'Temperley', provinciaId: '06' },
      { id: '06-121', nombre: 'Villa Adelina', provinciaId: '06' },
      { id: '06-122', nombre: 'Villa Ballester', provinciaId: '06' },
      { id: '06-123', nombre: 'Villa Bosch', provinciaId: '06' },
      { id: '06-124', nombre: 'Villa Celina', provinciaId: '06' },
      { id: '06-125', nombre: 'Villa Centenario', provinciaId: '06' },
      { id: '06-126', nombre: 'Villa Domínico', provinciaId: '06' },
      { id: '06-127', nombre: 'Villa Fiorito', provinciaId: '06' },
      { id: '06-128', nombre: 'Villa Luzuriaga', provinciaId: '06' },
      { id: '06-129', nombre: 'Villa Martelli', provinciaId: '06' },
      { id: '06-130', nombre: 'Villa Tesei', provinciaId: '06' },
      { id: '06-131', nombre: 'Virrey del Pino', provinciaId: '06' },
      { id: '06-132', nombre: 'Wilde', provinciaId: '06' },
      { id: '06-133', nombre: 'William C. Morris', provinciaId: '06' },
    ],
    
    // Catamarca (localidades mejoradas)
    '10': [
      { id: '10-001', nombre: 'San Fernando del Valle de Catamarca', provinciaId: '10' },
      { id: '10-002', nombre: 'Andalgalá', provinciaId: '10' },
      { id: '10-003', nombre: 'Belén', provinciaId: '10' },
      { id: '10-004', nombre: 'Santa María', provinciaId: '10' },
      { id: '10-005', nombre: 'Tinogasta', provinciaId: '10' },
      { id: '10-006', nombre: 'Valle Viejo', provinciaId: '10' },
      { id: '10-007', nombre: 'Fiambalá', provinciaId: '10' },
      { id: '10-008', nombre: 'Recreo', provinciaId: '10' },
      { id: '10-009', nombre: 'La Puerta', provinciaId: '10' },
      { id: '10-010', nombre: 'Capayán', provinciaId: '10' },
      { id: '10-011', nombre: 'Hualfín', provinciaId: '10' },
      { id: '10-012', nombre: 'Londres', provinciaId: '10' },
      { id: '10-013', nombre: 'Pomán', provinciaId: '10' },
      { id: '10-014', nombre: 'Saujil', provinciaId: '10' },
      { id: '10-015', nombre: 'Ancasti', provinciaId: '10' },
      { id: '10-016', nombre: 'El Rodeo', provinciaId: '10' },
      { id: '10-017', nombre: 'Icaño', provinciaId: '10' },
      { id: '10-018', nombre: 'La Merced', provinciaId: '10' },
      { id: '10-019', nombre: 'Miraflores', provinciaId: '10' },
      { id: '10-020', nombre: 'Paclín', provinciaId: '10' },
      { id: '10-021', nombre: 'San José', provinciaId: '10' },
      { id: '10-022', nombre: 'Santa Rosa', provinciaId: '10' },
      { id: '10-023', nombre: 'El Alto', provinciaId: '10' },
      { id: '10-024', nombre: 'Huillapima', provinciaId: '10' },
      { id: '10-025', nombre: 'Los Altos', provinciaId: '10' },
    ],
    
    // Córdoba (localidades mejoradas con La Calera)
    '14': [
      { id: '14-001', nombre: 'Córdoba', provinciaId: '14' },
      { id: '14-002', nombre: 'Villa María', provinciaId: '14' },
      { id: '14-003', nombre: 'Río Cuarto', provinciaId: '14' },
      { id: '14-004', nombre: 'San Francisco', provinciaId: '14' },
      { id: '14-005', nombre: 'Villa Carlos Paz', provinciaId: '14' },
      { id: '14-006', nombre: 'Río Tercero', provinciaId: '14' },
      { id: '14-007', nombre: 'Alta Gracia', provinciaId: '14' },
      { id: '14-008', nombre: 'Bell Ville', provinciaId: '14' },
      { id: '14-009', nombre: 'Cosquín', provinciaId: '14' },
      { id: '14-010', nombre: 'La Falda', provinciaId: '14' },
      { id: '14-011', nombre: 'Jesús María', provinciaId: '14' },
      { id: '14-012', nombre: 'Villa Dolores', provinciaId: '14' },
      { id: '14-013', nombre: 'Dean Funes', provinciaId: '14' },
      { id: '14-014', nombre: 'Cruz del Eje', provinciaId: '14' },
      { id: '14-015', nombre: 'Marcos Juárez', provinciaId: '14' },
      { id: '14-016', nombre: 'Laboulaye', provinciaId: '14' },
      { id: '14-017', nombre: 'Villa Allende', provinciaId: '14' },
      { id: '14-018', nombre: 'Villa Nueva', provinciaId: '14' },
      { id: '14-019', nombre: 'Arroyito', provinciaId: '14' },
      { id: '14-020', nombre: 'Corral de Bustos', provinciaId: '14' },
      { id: '14-021', nombre: 'La Carlota', provinciaId: '14' },
      { id: '14-022', nombre: 'Las Varillas', provinciaId: '14' },
      { id: '14-023', nombre: 'Morteros', provinciaId: '14' },
      { id: '14-024', nombre: 'Oliva', provinciaId: '14' },
      { id: '14-025', nombre: 'San Francisco del Chañar', provinciaId: '14' },
      { id: '14-026', nombre: 'Villa del Rosario', provinciaId: '14' },
      { id: '14-027', nombre: 'Oncativo', provinciaId: '14' },
      { id: '14-028', nombre: 'Hernando', provinciaId: '14' },
      { id: '14-029', nombre: 'Río Segundo', provinciaId: '14' },
      { id: '14-030', nombre: 'Unquillo', provinciaId: '14' },
      { id: '14-031', nombre: 'Capilla del Monte', provinciaId: '14' },
      { id: '14-032', nombre: 'Santa Rosa de Calamuchita', provinciaId: '14' },
      { id: '14-033', nombre: 'Mina Clavero', provinciaId: '14' },
      { id: '14-034', nombre: 'Huerta Grande', provinciaId: '14' },
      { id: '14-035', nombre: 'Villa General Belgrano', provinciaId: '14' },
      { id: '14-036', nombre: 'James Craik', provinciaId: '14' },
      { id: '14-037', nombre: 'Monte Buey', provinciaId: '14' },
      { id: '14-038', nombre: 'Villa Rumipal', provinciaId: '14' },
      { id: '14-039', nombre: 'Embalse', provinciaId: '14' },
      { id: '14-040', nombre: 'La Cruz', provinciaId: '14' },
      { id: '14-041', nombre: 'Villa Giardino', provinciaId: '14' },
      { id: '14-042', nombre: 'Salsipuedes', provinciaId: '14' },
      { id: '14-043', nombre: 'Malvinas Argentinas', provinciaId: '14' },
      { id: '14-044', nombre: 'Villa Cura Brochero', provinciaId: '14' },
      { id: '14-045', nombre: 'Non', provinciaId: '14' },
      { id: '14-046', nombre: 'Villa de Soto', provinciaId: '14' },
      { id: '14-047', nombre: 'La Para', provinciaId: '14' },
      { id: '14-048', nombre: 'Balnearia', provinciaId: '14' },
      { id: '14-049', nombre: 'Seeber', provinciaId: '14' },
      { id: '14-050', nombre: 'Devoto', provinciaId: '14' },
      { id: '14-051', nombre: 'La Calera', provinciaId: '14' }, // Agregada La Calera
      { id: '14-052', nombre: 'Villa Carlos Paz', provinciaId: '14' },
      { id: '14-053', nombre: 'San Agustín', provinciaId: '14' },
      { id: '14-054', nombre: 'Colonia Caroya', provinciaId: '14' },
      { id: '14-055', nombre: 'Colonia Tirolesa', provinciaId: '14' },
      { id: '14-056', nombre: 'Villa Santa Cruz del Lago', provinciaId: '14' },
      { id: '14-057', nombre: 'Valle Hermoso', provinciaId: '14' },
      { id: '14-058', nombre: 'La Cumbre', provinciaId: '14' },
      { id: '14-059', nombre: 'Los Cocos', provinciaId: '14' },
      { id: '14-060', nombre: 'La Serranita', provinciaId: '14' },
    ],
    
    // Corrientes (localidades expandidas)
    '18': [
      { id: '18-001', nombre: 'Corrientes', provinciaId: '18' },
      { id: '18-002', nombre: 'Goya', provinciaId: '18' },
      { id: '18-003', nombre: 'Curuzú Cuatiá', provinciaId: '18' },
      { id: '18-004', nombre: 'Paso de los Libres', provinciaId: '18' },
      { id: '18-005', nombre: 'Mercedes', provinciaId: '18' },
      { id: '18-006', nombre: 'Santo Tomé', provinciaId: '18' },
      { id: '18-007', nombre: 'Esquina', provinciaId: '18' },
      { id: '18-008', nombre: 'Bella Vista', provinciaId: '18' },
      { id: '18-009', nombre: 'Monte Caseros', provinciaId: '18' },
      { id: '18-010', nombre: 'Ituzaingó', provinciaId: '18' },
      { id: '18-011', nombre: 'Saladas', provinciaId: '18' },
      { id: '18-012', nombre: 'Empedrado', provinciaId: '18' },
      { id: '18-013', nombre: 'Virasoro', provinciaId: '18' },
      { id: '18-014', nombre: 'Gobernador Virasoro', provinciaId: '18' },
      { id: '18-015', nombre: 'Alvear', provinciaId: '18' },
      { id: '18-016', nombre: 'San Luis del Palmar', provinciaId: '18' },
      { id: '18-017', nombre: 'San Cosme', provinciaId: '18' },
      { id: '18-018', nombre: 'Itatí', provinciaId: '18' },
      { id: '18-019', nombre: 'San Miguel', provinciaId: '18' },
      { id: '18-020', nombre: 'Loreto', provinciaId: '18' },
      { id: '18-021', nombre: 'Yapeyú', provinciaId: '18' },
      { id: '18-022', nombre: 'La Cruz', provinciaId: '18' },
      { id: '18-023', nombre: 'Sauce', provinciaId: '18' },
      { id: '18-024', nombre: 'Chavarría', provinciaId: '18' },
      { id: '18-025', nombre: 'Mburucuyá', provinciaId: '18' },
    ],
    
    // Chaco (localidades expandidas)
    '22': [
      { id: '22-001', nombre: 'Resistencia', provinciaId: '22' },
      { id: '22-002', nombre: 'Presidencia Roque Sáenz Peña', provinciaId: '22' },
      { id: '22-003', nombre: 'Villa Ángela', provinciaId: '22' },
      { id: '22-004', nombre: 'Charata', provinciaId: '22' },
      { id: '22-005', nombre: 'General San Martín', provinciaId: '22' },
      { id: '22-006', nombre: 'Barranqueras', provinciaId: '22' },
      { id: '22-007', nombre: 'Quitilipi', provinciaId: '22' },
      { id: '22-008', nombre: 'Las Breñas', provinciaId: '22' },
      { id: '22-009', nombre: 'Fontana', provinciaId: '22' },
      { id: '22-010', nombre: 'Castelli', provinciaId: '22' },
      { id: '22-011', nombre: 'Villa Berthet', provinciaId: '22' },
      { id: '22-012', nombre: 'Machagai', provinciaId: '22' },
      { id: '22-013', nombre: 'General Pinedo', provinciaId: '22' },
      { id: '22-014', nombre: 'Hermoso Campo', provinciaId: '22' },
      { id: '22-015', nombre: 'Corzuela', provinciaId: '22' },
      { id: '22-016', nombre: 'La Escondida', provinciaId: '22' },
      { id: '22-017', nombre: 'Laguna Blanca', provinciaId: '22' },
      { id: '22-018', nombre: 'Pampa del Infierno', provinciaId: '22' },
      { id: '22-019', nombre: 'Tres Isletas', provinciaId: '22' },
      { id: '22-020', nombre: 'Concepción del Bermejo', provinciaId: '22' },
      { id: '22-021', nombre: 'Los Frentones', provinciaId: '22' },
      { id: '22-022', nombre: 'Colonia Benítez', provinciaId: '22' },
      { id: '22-023', nombre: 'Margarita Belén', provinciaId: '22' },
      { id: '22-024', nombre: 'Puerto Vilelas', provinciaId: '22' },
      { id: '22-025', nombre: 'Samuhú', provinciaId: '22' },
    ],
    
    // Chubut (localidades expandidas)
    '26': [
      { id: '26-001', nombre: 'Rawson', provinciaId: '26' },
      { id: '26-002', nombre: 'Comodoro Rivadavia', provinciaId: '26' },
      { id: '26-003', nombre: 'Trelew', provinciaId: '26' },
      { id: '26-004', nombre: 'Puerto Madryn', provinciaId: '26' },
      { id: '26-005', nombre: 'Esquel', provinciaId: '26' },
      { id: '26-006', nombre: 'Sarmiento', provinciaId: '26' },
      { id: '26-007', nombre: 'Gaiman', provinciaId: '26' },
      { id: '26-008', nombre: 'Rada Tilly', provinciaId: '26' },
      { id: '26-009', nombre: 'Dolavon', provinciaId: '26' },
      { id: '26-010', nombre: 'Puerto Pirámides', provinciaId: '26' },
      { id: '26-011', nombre: 'Gobernador Costa', provinciaId: '26' },
      { id: '26-012', nombre: 'Trevelin', provinciaId: '26' },
      { id: '26-013', nombre: 'Camarones', provinciaId: '26' },
      { id: '26-014', nombre: 'Alto Río Senguer', provinciaId: '26' },
      { id: '26-015', nombre: 'Río Mayo', provinciaId: '26' },
      { id: '26-016', nombre: 'El Maitén', provinciaId: '26' },
      { id: '26-017', nombre: 'José de San Martín', provinciaId: '26' },
      { id: '26-018', nombre: 'Tecka', provinciaId: '26' },
      { id: '26-019', nombre: 'Corcovado', provinciaId: '26' },
      { id: '26-020', nombre: 'Lago Puelo', provinciaId: '26' },
      { id: '26-021', nombre: 'Epuyén', provinciaId: '26' },
      { id: '26-022', nombre: 'Cholila', provinciaId: '26' },
      { id: '26-023', nombre: '28 de Julio', provinciaId: '26' },
      { id: '26-024', nombre: 'Gualjaina', provinciaId: '26' },
      { id: '26-025', nombre: 'Gan Gan', provinciaId: '26' },
    ],
    
    // Entre Ríos (localidades expandidas)
    '30': [
      { id: '30-001', nombre: 'Paraná', provinciaId: '30' },
      { id: '30-002', nombre: 'Concordia', provinciaId: '30' },
      { id: '30-003', nombre: 'Gualeguaychú', provinciaId: '30' },
      { id: '30-004', nombre: 'Concepción del Uruguay', provinciaId: '30' },
      { id: '30-005', nombre: 'Gualeguay', provinciaId: '30' },
      { id: '30-006', nombre: 'Victoria', provinciaId: '30' },
      { id: '30-007', nombre: 'Villaguay', provinciaId: '30' },
      { id: '30-008', nombre: 'Colón', provinciaId: '30' },
      { id: '30-009', nombre: 'Chajarí', provinciaId: '30' },
      { id: '30-010', nombre: 'Federación', provinciaId: '30' },
      { id: '30-011', nombre: 'La Paz', provinciaId: '30' },
      { id: '30-012', nombre: 'Nogoyá', provinciaId: '30' },
      { id: '30-013', nombre: 'Crespo', provinciaId: '30' },
      { id: '30-014', nombre: 'Diamante', provinciaId: '30' },
      { id: '30-015', nombre: 'San José', provinciaId: '30' },
      { id: '30-016', nombre: 'Villa Elisa', provinciaId: '30' },
      { id: '30-017', nombre: 'San Salvador', provinciaId: '30' },
      { id: '30-018', nombre: 'Rosario del Tala', provinciaId: '30' },
      { id: '30-019', nombre: 'Basavilbaso', provinciaId: '30' },
      { id: '30-020', nombre: 'Cerrito', provinciaId: '30' },
      { id: '30-021', nombre: 'General Campos', provinciaId: '30' },
      { id: '30-022', nombre: 'Hasenkamp', provinciaId: '30' },
      { id: '30-023', nombre: 'Hernandarias', provinciaId: '30' },
      { id: '30-024', nombre: 'Larroque', provinciaId: '30' },
      { id: '30-025', nombre: 'Oro Verde', provinciaId: '30' },
    ],
    
    // Formosa (localidades expandidas)
    '34': [
      { id: '34-001', nombre: 'Formosa', provinciaId: '34' },
      { id: '34-002', nombre: 'Clorinda', provinciaId: '34' },
      { id: '34-003', nombre: 'Pirané', provinciaId: '34' },
      { id: '34-004', nombre: 'El Colorado', provinciaId: '34' },
      { id: '34-005', nombre: 'Las Lomitas', provinciaId: '34' },
      { id: '34-006', nombre: 'Ingeniero Juárez', provinciaId: '34' },
      { id: '34-007', nombre: 'Laguna Blanca', provinciaId: '34' },
      { id: '34-008', nombre: 'Comandante Fontana', provinciaId: '34' },
      { id: '34-009', nombre: 'Ibarreta', provinciaId: '34' },
      { id: '34-010', nombre: 'Laguna Naick-Neck', provinciaId: '34' },
      { id: '34-011', nombre: 'Estanislao del Campo', provinciaId: '34' },
      { id: '34-012', nombre: 'General Lucio V. Mansilla', provinciaId: '34' },
      { id: '34-013', nombre: 'Herradura', provinciaId: '34' },
      { id: '34-014', nombre: 'Mayor Villafañe', provinciaId: '34' },
      { id: '34-015', nombre: 'Palo Santo', provinciaId: '34' },
      { id: '34-016', nombre: 'Riacho He-Hé', provinciaId: '34' },
      { id: '34-017', nombre: 'San Hilario', provinciaId: '34' },
      { id: '34-018', nombre: 'Subteniente Perín', provinciaId: '34' },
      { id: '34-019', nombre: 'Tres Lagunas', provinciaId: '34' },
      { id: '34-020', nombre: 'Villa Dos Trece', provinciaId: '34' },
    ],
    
    // Jujuy (localidades expandidas)
    '38': [
      { id: '38-001', nombre: 'San Salvador de Jujuy', provinciaId: '38' },
      { id: '38-002', nombre: 'Palpala', provinciaId: '38' },
      { id: '38-003', nombre: 'San Pedro', provinciaId: '38' },
      { id: '38-004', nombre: 'Libertador General San Martín', provinciaId: '38' },
      { id: '38-005', nombre: 'La Quiaca', provinciaId: '38' },
      { id: '38-006', nombre: 'Humahuaca', provinciaId: '38' },
      { id: '38-007', nombre: 'Fraile Pintado', provinciaId: '38' },
      { id: '38-008', nombre: 'Perico', provinciaId: '38' },
      { id: '38-009', nombre: 'El Carmen', provinciaId: '38' },
      { id: '38-010', nombre: 'Monterrico', provinciaId: '38' },
      { id: '38-011', nombre: 'Tilcara', provinciaId: '38' },
      { id: '38-012', nombre: 'La Esperanza', provinciaId: '38' },
      { id: '38-013', nombre: 'Abra Pampa', provinciaId: '38' },
      { id: '38-014', nombre: 'Caimancito', provinciaId: '38' },
      { id: '38-015', nombre: 'Calilegua', provinciaId: '38' },
      { id: '38-016', nombre: 'El Talar', provinciaId: '38' },
      { id: '38-017', nombre: 'La Mendieta', provinciaId: '38' },
      { id: '38-018', nombre: 'Maimará', provinciaId: '38' },
      { id: '38-019', nombre: 'Pampa Blanca', provinciaId: '38' },
      { id: '38-020', nombre: 'Purmamarca', provinciaId: '38' },
      { id: '38-021', nombre: 'San Antonio', provinciaId: '38' },
      { id: '38-022', nombre: 'Santa Clara', provinciaId: '38' },
      { id: '38-023', nombre: 'Susques', provinciaId: '38' },
      { id: '38-024', nombre: 'Uquía', provinciaId: '38' },
      { id: '38-025', nombre: 'Volcán', provinciaId: '38' },
    ],
    
    // La Pampa (localidades expandidas)
    '42': [
      { id: '42-001', nombre: 'Santa Rosa', provinciaId: '42' },
      { id: '42-002', nombre: 'General Pico', provinciaId: '42' },
      { id: '42-003', nombre: 'General Acha', provinciaId: '42' },
      { id: '42-004', nombre: 'Toay', provinciaId: '42' },
      { id: '42-005', nombre: 'Realicó', provinciaId: '42' },
      { id: '42-006', nombre: 'Eduardo Castex', provinciaId: '42' },
      { id: '42-007', nombre: 'Intendente Alvear', provinciaId: '42' },
      { id: '42-008', nombre: 'Victorica', provinciaId: '42' },
      { id: '42-009', nombre: 'Macachín', provinciaId: '42' },
      { id: '42-010', nombre: 'Ingeniero Luiggi', provinciaId: '42' },
      { id: '42-011', nombre: 'Quemú Quemú', provinciaId: '42' },
      { id: '42-012', nombre: 'Alta Italia', provinciaId: '42' },
      { id: '42-013', nombre: 'Bernardo Larroudé', provinciaId: '42' },
      { id: '42-014', nombre: 'Caleufú', provinciaId: '42' },
      { id: '42-015', nombre: 'Carro Quemado', provinciaId: '42' },
      { id: '42-016', nombre: 'Catriló', provinciaId: '42' },
      { id: '42-017', nombre: 'Colonia Barón', provinciaId: '42' },
      { id: '42-018', nombre: 'Doblas', provinciaId: '42' },
      { id: '42-019', nombre: 'General Campos', provinciaId: '42' },
      { id: '42-020', nombre: 'Guatraché', provinciaId: '42' },
      { id: '42-021', nombre: 'Jacinto Arauz', provinciaId: '42' },
      { id: '42-022', nombre: 'La Adela', provinciaId: '42' },
      { id: '42-023', nombre: 'Lonquimay', provinciaId: '42' },
      { id: '42-024', nombre: 'Luan Toro', provinciaId: '42' },
      { id: '42-025', nombre: 'Metileo', provinciaId: '42' },
    ],
    
    // La Rioja (localidades expandidas)
    '46': [
      { id: '46-001', nombre: 'La Rioja', provinciaId: '46' },
      { id: '46-002', nombre: 'Chilecito', provinciaId: '46' },
      { id: '46-003', nombre: 'Chamical', provinciaId: '46' },
      { id: '46-004', nombre: 'Aimogasta', provinciaId: '46' },
      { id: '46-005', nombre: 'Villa Unión', provinciaId: '46' },
      { id: '46-006', nombre: 'Arauco', provinciaId: '46' },
      { id: '46-007', nombre: 'Famatina', provinciaId: '46' },
      { id: '46-008', nombre: 'Chepes', provinciaId: '46' },
      { id: '46-009', nombre: 'Ulapes', provinciaId: '46' },
      { id: '46-010', nombre: 'Villa Sanagasta', provinciaId: '46' },
      { id: '46-011', nombre: 'Milagro', provinciaId: '46' },
      { id: '46-012', nombre: 'Patquía', provinciaId: '46' },
      { id: '46-013', nombre: 'San Blas de los Sauces', provinciaId: '46' },
      { id: '46-014', nombre: 'Tama', provinciaId: '46' },
      { id: '46-015', nombre: 'Vinchina', provinciaId: '46' },
      { id: '46-016', nombre: 'Castro Barros', provinciaId: '46' },
      { id: '46-017', nombre: 'General Belgrano', provinciaId: '46' },
      { id: '46-018', nombre: 'General Lamadrid', provinciaId: '46' },
      { id: '46-019', nombre: 'Independencia', provinciaId: '46' },
      { id: '46-020', nombre: 'Rosario Vera Peñaloza', provinciaId: '46' },
      { id: '46-021', nombre: 'Sanagasta', provinciaId: '46' },
      { id: '46-022', nombre: 'Capital', provinciaId: '46' },
      { id: '46-023', nombre: 'Chilecito', provinciaId: '46' },
      { id: '46-024', nombre: 'Famatina', provinciaId: '46' },
      { id: '46-025', nombre: 'General Ángel V. Peñaloza', provinciaId: '46' },
    ],
    
    // Mendoza (localidades expandidas)
    '50': [
      { id: '50-001', nombre: 'Mendoza', provinciaId: '50' },
      { id: '50-002', nombre: 'San Rafael', provinciaId: '50' },
      { id: '50-003', nombre: 'Godoy Cruz', provinciaId: '50' },
      { id: '50-004', nombre: 'Guaymallén', provinciaId: '50' },
      { id: '50-005', nombre: 'Las Heras', provinciaId: '50' },
      { id: '50-006', nombre: 'Maipú', provinciaId: '50' },
      { id: '50-007', nombre: 'Luján de Cuyo', provinciaId: '50' },
      { id: '50-008', nombre: 'San Martín', provinciaId: '50' },
      { id: '50-009', nombre: 'Tunuyán', provinciaId: '50' },
      { id: '50-010', nombre: 'Rivadavia', provinciaId: '50' },
      { id: '50-011', nombre: 'Junín', provinciaId: '50' },
      { id: '50-012', nombre: 'Lavalle', provinciaId: '50' },
      { id: '50-013', nombre: 'Tupungato', provinciaId: '50' },
      { id: '50-014', nombre: 'General Alvear', provinciaId: '50' },
      { id: '50-015', nombre: 'Malargüe', provinciaId: '50' },
      { id: '50-016', nombre: 'San Carlos', provinciaId: '50' },
      { id: '50-017', nombre: 'La Paz', provinciaId: '50' },
      { id: '50-018', nombre: 'Santa Rosa', provinciaId: '50' },
      { id: '50-019', nombre: 'Bowen', provinciaId: '50' },
      { id: '50-020', nombre: 'Cacheuta', provinciaId: '50' },
      { id: '50-021', nombre: 'Capilla del Rosario', provinciaId: '50' },
      { id: '50-022', nombre: 'Chacras de Coria', provinciaId: '50' },
      { id: '50-023', nombre: 'Coquimbito', provinciaId: '50' },
      { id: '50-024', nombre: 'Costa de Araujo', provinciaId: '50' },
      { id: '50-025', nombre: 'El Nihuil', provinciaId: '50' },
    ],
    
    // Misiones (localidades expandidas)
    '54': [
      { id: '54-001', nombre: 'Posadas', provinciaId: '54' },
      { id: '54-002', nombre: 'Oberá', provinciaId: '54' },
      { id: '54-003', nombre: 'Eldorado', provinciaId: '54' },
      { id: '54-004', nombre: 'Puerto Iguazú', provinciaId: '54' },
      { id: '54-005', nombre: 'Apóstoles', provinciaId: '54' },
      { id: '54-006', nombre: 'Leandro N. Alem', provinciaId: '54' },
      { id: '54-007', nombre: 'Jardín América', provinciaId: '54' },
      { id: '54-008', nombre: 'Garupá', provinciaId: '54' },
      { id: '54-009', nombre: 'Aristóbulo del Valle', provinciaId: '54' },
      { id: '54-010', nombre: 'Montecarlo', provinciaId: '54' },
      { id: '54-011', nombre: 'San Vicente', provinciaId: '54' },
      { id: '54-012', nombre: 'Puerto Rico', provinciaId: '54' },
      { id: '54-013', nombre: 'Candelaria', provinciaId: '54' },
      { id: '54-014', nombre: 'San Ignacio', provinciaId: '54' },
      { id: '54-015', nombre: 'Wanda', provinciaId: '54' },
      { id: '54-016', nombre: 'Campo Grande', provinciaId: '54' },
      { id: '54-017', nombre: 'Campo Ramón', provinciaId: '54' },
      { id: '54-018', nombre: 'Colonia Aurora', provinciaId: '54' },
      { id: '54-019', nombre: 'Dos de Mayo', provinciaId: '54' },
      { id: '54-020', nombre: 'El Soberbio', provinciaId: '54' },
      { id: '54-021', nombre: 'Gobernador Roca', provinciaId: '54' },
      { id: '54-022', nombre: 'Hipólito Yrigoyen', provinciaId: '54' },
      { id: '54-023', nombre: 'Panambí', provinciaId: '54' },
      { id: '54-024', nombre: 'Puerto Esperanza', provinciaId: '54' },
      { id: '54-025', nombre: 'Ruiz de Montoya', provinciaId: '54' },
    ],
    
    // Neuquén (localidades expandidas)
    '58': [
      { id: '58-001', nombre: 'Neuquén', provinciaId: '58' },
      { id: '58-002', nombre: 'San Martín de los Andes', provinciaId: '58' },
      { id: '58-003', nombre: 'Zapala', provinciaId: '58' },
      { id: '58-004', nombre: 'Cutral Có', provinciaId: '58' },
      { id: '58-005', nombre: 'Plaza Huincul', provinciaId: '58' },
      { id: '58-006', nombre: 'Centenario', provinciaId: '58' },
      { id: '58-007', nombre: 'Villa La Angostura', provinciaId: '58' },
      { id: '58-008', nombre: 'Plottier', provinciaId: '58' },
      { id: '58-009', nombre: 'Junín de los Andes', provinciaId: '58' },
      { id: '58-010', nombre: 'Chos Malal', provinciaId: '58' },
      { id: '58-011', nombre: 'Senillosa', provinciaId: '58' },
      { id: '58-012', nombre: 'Loncopué', provinciaId: '58' },
      { id: '58-013', nombre: 'Aluminé', provinciaId: '58' },
      { id: '58-014', nombre: 'Andacollo', provinciaId: '58' },
      { id: '58-015', nombre: 'Añelo', provinciaId: '58' },
      { id: '58-016', nombre: 'Bajada del Agrio', provinciaId: '58' },
      { id: '58-017', nombre: 'Buta Ranquil', provinciaId: '58' },
      { id: '58-018', nombre: 'Caviahue', provinciaId: '58' },
      { id: '58-019', nombre: 'El Huecú', provinciaId: '58' },
      { id: '58-020', nombre: 'Las Coloradas', provinciaId: '58' },
      { id: '58-021', nombre: 'Las Lajas', provinciaId: '58' },
      { id: '58-022', nombre: 'Los Miches', provinciaId: '58' },
      { id: '58-023', nombre: 'Piedra del Águila', provinciaId: '58' },
      { id: '58-024', nombre: 'Pino Hachado', provinciaId: '58' },
      { id: '58-025', nombre: 'Rincón de los Sauces', provinciaId: '58' },
    ],
    
    // Río Negro (localidades expandidas)
    '62': [
      { id: '62-001', nombre: 'Viedma', provinciaId: '62' },
      { id: '62-002', nombre: 'San Carlos de Bariloche', provinciaId: '62' },
      { id: '62-003', nombre: 'General Roca', provinciaId: '62' },
      { id: '62-004', nombre: 'Cipolletti', provinciaId: '62' },
      { id: '62-005', nombre: 'Allen', provinciaId: '62' },
      { id: '62-006', nombre: 'Villa Regina', provinciaId: '62' },
      { id: '62-007', nombre: 'El Bolsón', provinciaId: '62' },
      { id: '62-008', nombre: 'Catriel', provinciaId: '62' },
      { id: '62-009', nombre: 'Cinco Saltos', provinciaId: '62' },
      { id: '62-010', nombre: 'Luis Beltrán', provinciaId: '62' },
      { id: '62-011', nombre: 'Choele Choel', provinciaId: '62' },
      { id: '62-012', nombre: 'San Antonio Oeste', provinciaId: '62' },
      { id: '62-013', nombre: 'Sierra Grande', provinciaId: '62' },
      { id: '62-014', nombre: 'Campo Grande', provinciaId: '62' },
      { id: '62-015', nombre: 'Comallo', provinciaId: '62' },
      { id: '62-016', nombre: 'Coronel Belisle', provinciaId: '62' },
      { id: '62-017', nombre: 'Dina Huapi', provinciaId: '62' },
      { id: '62-018', nombre: 'El Cuy', provinciaId: '62' },
      { id: '62-019', nombre: 'General Conesa', provinciaId: '62' },
      { id: '62-020', nombre: 'General Enrique Godoy', provinciaId: '62' },
      { id: '62-021', nombre: 'Ingeniero Jacobacci', provinciaId: '62' },
      { id: '62-022', nombre: 'Lamarque', provinciaId: '62' },
      { id: '62-023', nombre: 'Los Menucos', provinciaId: '62' },
      { id: '62-024', nombre: 'Maquinchao', provinciaId: '62' },
      { id: '62-025', nombre: 'Río Colorado', provinciaId: '62' },
    ],
    
    // Salta (localidades expandidas)
    '66': [
      { id: '66-001', nombre: 'Salta', provinciaId: '66' },
      { id: '66-002', nombre: 'San Ramón de la Nueva Orán', provinciaId: '66' },
      { id: '66-003', nombre: 'Tartagal', provinciaId: '66' },
      { id: '66-004', nombre: 'Metán', provinciaId: '66' },
      { id: '66-005', nombre: 'Cafayate', provinciaId: '66' },
      { id: '66-006', nombre: 'Rosario de la Frontera', provinciaId: '66' },
      { id: '66-007', nombre: 'General Güemes', provinciaId: '66' },
      { id: '66-008', nombre: 'El Carmen', provinciaId: '66' },
      { id: '66-009', nombre: 'Joaquín V. González', provinciaId: '66' },
      { id: '66-010', nombre: 'Embarcación', provinciaId: '66' },
      { id: '66-011', nombre: 'Pichanal', provinciaId: '66' },
      { id: '66-012', nombre: 'Cerrillos', provinciaId: '66' },
      { id: '66-013', nombre: 'La Caldera', provinciaId: '66' },
      { id: '66-014', nombre: 'Chicoana', provinciaId: '66' },
      { id: '66-015', nombre: 'Cachi', provinciaId: '66' },
      { id: '66-016', nombre: 'Molinos', provinciaId: '66' },
      { id: '66-017', nombre: 'Campo Quijano', provinciaId: '66' },
      { id: '66-018', nombre: 'General Ballivián', provinciaId: '66' },
      { id: '66-019', nombre: 'General Mosconi', provinciaId: '66' },
      { id: '66-020', nombre: 'Guachipas', provinciaId: '66' },
      { id: '66-021', nombre: 'Iruya', provinciaId: '66' },
      { id: '66-022', nombre: 'La Viña', provinciaId: '66' },
      { id: '66-023', nombre: 'Los Toldos', provinciaId: '66' },
      { id: '66-024', nombre: 'Payogasta', provinciaId: '66' },
      { id: '66-025', nombre: 'San Antonio de los Cobres', provinciaId: '66' },
    ],
    
    // San Juan (localidades expandidas)
    '70': [
      { id: '70-001', nombre: 'San Juan', provinciaId: '70' },
      { id: '70-002', nombre: 'Rawson', provinciaId: '70' },
      { id: '70-003', nombre: 'Chimbas', provinciaId: '70' },
      { id: '70-004', nombre: 'Rivadavia', provinciaId: '70' },
      { id: '70-005', nombre: 'Santa Lucía', provinciaId: '70' },
      { id: '70-006', nombre: 'Caucete', provinciaId: '70' },
      { id: '70-007', nombre: 'Pocito', provinciaId: '70' },
      { id: '70-008', nombre: 'Albardón', provinciaId: '70' },
      { id: '70-009', nombre: 'Nueve de Julio', provinciaId: '70' },
      { id: '70-010', nombre: 'Jáchal', provinciaId: '70' },
      { id: '70-011', nombre: 'Veinticinco de Mayo', provinciaId: '70' },
      { id: '70-012', nombre: 'Calingasta', provinciaId: '70' },
      { id: '70-013', nombre: 'Iglesia', provinciaId: '70' },
      { id: '70-014', nombre: 'Valle Fértil', provinciaId: '70' },
      { id: '70-015', nombre: 'Angaco', provinciaId: '70' },
      { id: '70-016', nombre: 'Zonda', provinciaId: '70' },
      { id: '70-017', nombre: 'Ullum', provinciaId: '70' },
      { id: '70-018', nombre: 'Sarmiento', provinciaId: '70' },
      { id: '70-019', nombre: 'San Martín', provinciaId: '70' },
      { id: '70-020', nombre: '9 de Julio', provinciaId: '70' },
      { id: '70-021', nombre: 'Bella Vista', provinciaId: '70' },
      { id: '70-022', nombre: 'Carpintería', provinciaId: '70' },
      { id: '70-023', nombre: 'Las Flores', provinciaId: '70' },
      { id: '70-024', nombre: 'Villa Aberastain', provinciaId: '70' },
      { id: '70-025', nombre: 'Villa Basilio Nievas', provinciaId: '70' },
    ],
    
    // San Luis (localidades expandidas)
    '74': [
      { id: '74-001', nombre: 'San Luis', provinciaId: '74' },
      { id: '74-002', nombre: 'Villa Mercedes', provinciaId: '74' },
      { id: '74-003', nombre: 'Merlo', provinciaId: '74' },
      { id: '74-004', nombre: 'La Punta', provinciaId: '74' },
      { id: '74-005', nombre: 'Justo Daract', provinciaId: '74' },
      { id: '74-006', nombre: 'Villa de Praga', provinciaId: '74' },
      { id: '74-007', nombre: 'Tilisarao', provinciaId: '74' },
      { id: '74-008', nombre: 'Concarán', provinciaId: '74' },
      { id: '74-009', nombre: 'Carpintería', provinciaId: '74' },
      { id: '74-010', nombre: 'Santa Rosa del Conlara', provinciaId: '74' },
      { id: '74-011', nombre: 'Naschel', provinciaId: '74' },
      { id: '74-012', nombre: 'Quines', provinciaId: '74' },
      { id: '74-013', nombre: 'Luján', provinciaId: '74' },
      { id: '74-014', nombre: 'Buena Esperanza', provinciaId: '74' },
      { id: '74-015', nombre: 'Unión', provinciaId: '74' },
      { id: '74-016', nombre: 'Juan Jorba', provinciaId: '74' },
      { id: '74-017', nombre: 'Juan Llerena', provinciaId: '74' },
      { id: '74-018', nombre: 'La Toma', provinciaId: '74' },
      { id: '74-019', nombre: 'Lafinur', provinciaId: '74' },
      { id: '74-020', nombre: 'Los Molles', provinciaId: '74' },
      { id: '74-021', nombre: 'Nogolí', provinciaId: '74' },
      { id: '74-022', nombre: 'Papagayos', provinciaId: '74' },
      { id: '74-023', nombre: 'Renca', provinciaId: '74' },
      { id: '74-024', nombre: 'Saladillo', provinciaId: '74' },
      { id: '74-025', nombre: 'San Francisco del Monte de Oro', provinciaId: '74' },
    ],
    
    // Santa Cruz (localidades expandidas)
    '78': [
      { id: '78-001', nombre: 'Río Gallegos', provinciaId: '78' },
      { id: '78-002', nombre: 'Caleta Olivia', provinciaId: '78' },
      { id: '78-003', nombre: 'El Calafate', provinciaId: '78' },
      { id: '78-004', nombre: 'Pico Truncado', provinciaId: '78' },
      { id: '78-005', nombre: 'Puerto Deseado', provinciaId: '78' },
      { id: '78-006', nombre: 'Puerto San Julián', provinciaId: '78' },
      { id: '78-007', nombre: 'Río Turbio', provinciaId: '78' },
      { id: '78-008', nombre: 'Las Heras', provinciaId: '78' },
      { id: '78-009', nombre: 'Comandante Luis Piedra Buena', provinciaId: '78' },
      { id: '78-010', nombre: 'Gobernador Gregores', provinciaId: '78' },
      { id: '78-011', nombre: 'El Chaltén', provinciaId: '78' },
      { id: '78-012', nombre: 'Perito Moreno', provinciaId: '78' },
      { id: '78-013', nombre: '28 de Noviembre', provinciaId: '78' },
      { id: '78-014', nombre: 'Los Antiguos', provinciaId: '78' },
      { id: '78-015', nombre: 'Puerto Santa Cruz', provinciaId: '78' },
      { id: '78-016', nombre: 'Cañadón Seco', provinciaId: '78' },
      { id: '78-017', nombre: 'Fitz Roy', provinciaId: '78' },
      { id: '78-018', nombre: 'Jaramillo', provinciaId: '78' },
      { id: '78-019', nombre: 'Koluel Kaike', provinciaId: '78' },
      { id: '78-020', nombre: 'Las Heras', provinciaId: '78' },
      { id: '78-021', nombre: 'Pico Truncado', provinciaId: '78' },
      { id: '78-022', nombre: 'Puerto Deseado', provinciaId: '78' },
      { id: '78-023', nombre: 'Río Gallegos', provinciaId: '78' },
      { id: '78-024', nombre: 'San Julián', provinciaId: '78' },
      { id: '78-025', nombre: 'Tres Lagos', provinciaId: '78' },
    ],
    
    // Santa Fe (localidades expandidas)
    '82': [
      { id: '82-001', nombre: 'Santa Fe', provinciaId: '82' },
      { id: '82-002', nombre: 'Rosario', provinciaId: '82' },
      { id: '82-003', nombre: 'Rafaela', provinciaId: '82' },
      { id: '82-004', nombre: 'Venado Tuerto', provinciaId: '82' },
      { id: '82-005', nombre: 'Reconquista', provinciaId: '82' },
      { id: '82-006', nombre: 'Villa Gobernador Gálvez', provinciaId: '82' },
      { id: '82-007', nombre: 'Casilda', provinciaId: '82' },
      { id: '82-008', nombre: 'Esperanza', provinciaId: '82' },
      { id: '82-009', nombre: 'Santo Tomé', provinciaId: '82' },
      { id: '82-010', nombre: 'Cañada de Gómez', provinciaId: '82' },
      { id: '82-011', nombre: 'Funes', provinciaId: '82' },
      { id: '82-012', nombre: 'Gálvez', provinciaId: '82' },
      { id: '82-013', nombre: 'Firmat', provinciaId: '82' },
      { id: '82-014', nombre: 'Rufino', provinciaId: '82' },
      { id: '82-015', nombre: 'Sunchales', provinciaId: '82' },
      { id: '82-016', nombre: 'Vera', provinciaId: '82' },
      { id: '82-017', nombre: 'Villa Constitución', provinciaId: '82' },
      { id: '82-018', nombre: 'San Lorenzo', provinciaId: '82' },
      { id: '82-019', nombre: 'San Javier', provinciaId: '82' },
      { id: '82-020', nombre: 'Arroyo Seco', provinciaId: '82' },
      { id: '82-021', nombre: 'Capitán Bermúdez', provinciaId: '82' },
      { id: '82-022', nombre: 'Granadero Baigorria', provinciaId: '82' },
      { id: '82-023', nombre: 'Pérez', provinciaId: '82' },
      { id: '82-024', nombre: 'Roldán', provinciaId: '82' },
      { id: '82-025', nombre: 'Armstrong', provinciaId: '82' },
    ],
    
    // Santiago del Estero (localidades expandidas)
    '86': [
      { id: '86-001', nombre: 'Santiago del Estero', provinciaId: '86' },
      { id: '86-002', nombre: 'La Banda', provinciaId: '86' },
      { id: '86-003', nombre: 'Termas de Río Hondo', provinciaId: '86' },
      { id: '86-004', nombre: 'Frías', provinciaId: '86' },
      { id: '86-005', nombre: 'Añatuya', provinciaId: '86' },
      { id: '86-006', nombre: 'Fernández', provinciaId: '86' },
      { id: '86-007', nombre: 'Monte Quemado', provinciaId: '86' },
      { id: '86-008', nombre: 'Suncho Corral', provinciaId: '86' },
      { id: '86-009', nombre: 'Quimilí', provinciaId: '86' },
      { id: '86-010', nombre: 'Pinto', provinciaId: '86' },
      { id: '86-011', nombre: 'Villa Ojo de Agua', provinciaId: '86' },
      { id: '86-012', nombre: 'Bandera', provinciaId: '86' },
      { id: '86-013', nombre: 'Clodomira', provinciaId: '86' },
      { id: '86-014', nombre: 'El Bobadal', provinciaId: '86' },
      { id: '86-015', nombre: 'Loreto', provinciaId: '86' },
      { id: '86-016', nombre: 'Pozo Hondo', provinciaId: '86' },
      { id: '86-017', nombre: 'Selva', provinciaId: '86' },
      { id: '86-018', nombre: 'Sumampa', provinciaId: '86' },
      { id: '86-019', nombre: 'Villa Atamisqui', provinciaId: '86' },
      { id: '86-020', nombre: 'Villa General Mitre', provinciaId: '86' },
      { id: '86-021', nombre: 'Villa Río Hondo', provinciaId: '86' },
      { id: '86-022', nombre: 'Weisburd', provinciaId: '86' },
      { id: '86-023', nombre: 'Yanda', provinciaId: '86' },
      { id: '86-024', nombre: 'El Charco', provinciaId: '86' },
      { id: '86-025', nombre: 'Los Juríes', provinciaId: '86' },
    ],
    
    // Tucumán (localidades expandidas)
    '90': [
      { id: '90-001', nombre: 'San Miguel de Tucumán', provinciaId: '90' },
      { id: '90-002', nombre: 'Yerba Buena', provinciaId: '90' },
      { id: '90-003', nombre: 'Tafí Viejo', provinciaId: '90' },
      { id: '90-004', nombre: 'Concepción', provinciaId: '90' },
      { id: '90-005', nombre: 'Aguilares', provinciaId: '90' },
      { id: '90-006', nombre: 'Monteros', provinciaId: '90' },
      { id: '90-007', nombre: 'Famaillá', provinciaId: '90' },
      { id: '90-008', nombre: 'Banda del Río Salí', provinciaId: '90' },
      { id: '90-009', nombre: 'Alderetes', provinciaId: '90' },
      { id: '90-010', nombre: 'Bella Vista', provinciaId: '90' },
      { id: '90-011', nombre: 'Simoca', provinciaId: '90' },
      { id: '90-012', nombre: 'Burruyacú', provinciaId: '90' },
      { id: '90-013', nombre: 'La Cocha', provinciaId: '90' },
      { id: '90-014', nombre: 'Graneros', provinciaId: '90' },
      { id: '90-015', nombre: 'Lules', provinciaId: '90' },
      { id: '90-016', nombre: 'Tafí del Valle', provinciaId: '90' },
      { id: '90-017', nombre: 'Trancas', provinciaId: '90' },
      { id: '90-018', nombre: 'Cruz Alta', provinciaId: '90' },
      { id: '90-019', nombre: 'Leales', provinciaId: '90' },
      { id: '90-020', nombre: 'Río Chico', provinciaId: '90' },
      { id: '90-021', nombre: 'Chicligasta', provinciaId: '90' },
      { id: '90-022', nombre: 'Juan Bautista Alberdi', provinciaId: '90' },
      { id: '90-023', nombre: 'La Madrid', provinciaId: '90' },
      { id: '90-024', nombre: 'Monteros', provinciaId: '90' },
      { id: '90-025', nombre: 'San Pedro de Colalao', provinciaId: '90' },
    ],
    
    // Tierra del Fuego (localidades expandidas)
    '94': [
      { id: '94-001', nombre: 'Ushuaia', provinciaId: '94' },
      { id: '94-002', nombre: 'Río Grande', provinciaId: '94' },
      { id: '94-003', nombre: 'Tolhuin', provinciaId: '94' },
      { id: '94-004', nombre: 'Lago Escondido', provinciaId: '94' },
      { id: '94-005', nombre: 'San Sebastián', provinciaId: '94' },
      { id: '94-006', nombre: 'Cabo San Pablo', provinciaId: '94' },
      { id: '94-007', nombre: 'Estancia Harberton', provinciaId: '94' },
      { id: '94-008', nombre: 'Puerto Almanza', provinciaId: '94' },
      { id: '94-009', nombre: 'Puerto Williams', provinciaId: '94' },
      { id: '94-010', nombre: 'Camarones', provinciaId: '94' },
    ],
  };
  
  // Barrios de CABA (si necesitas una estructura más detallada)
  export const BARRIOS_CABA: Barrio[] = [
    { id: 'b-001', nombre: 'Palermo Hollywood', localidadId: '02-022' },
    { id: 'b-002', nombre: 'Palermo Soho', localidadId: '02-022' },
    { id: 'b-003', nombre: 'Belgrano R', localidadId: '02-005' },
    { id: 'b-004', nombre: 'Belgrano C', localidadId: '02-005' },
    { id: 'b-005', nombre: 'Barrio Norte', localidadId: '02-028' },
    { id: 'b-006', nombre: 'Abasto', localidadId: '02-002' },
    { id: 'b-007', nombre: 'Congreso', localidadId: '02-011' },
    { id: 'b-008', nombre: 'Microcentro', localidadId: '02-032' },
    { id: 'b-009', nombre: 'Puerto Madero Este', localidadId: '02-027' },
    { id: 'b-010', nombre: 'Puerto Madero Oeste', localidadId: '02-027' },
  ];
  
  /**
   * Obtener localidades por provincia
   */
  export const getLocalidadesByProvincia = (provinciaId: string): Localidad[] => {
    return LOCALIDADES[provinciaId] || [];
  };
  
  /**
   * Obtener barrios por localidad (especialmente para CABA)
   */
  export const getBarriosByLocalidad = (localidadId: string): Barrio[] => {
    return BARRIOS_CABA.filter(barrio => barrio.localidadId === localidadId);
  };
  
  /**
   * Buscar provincia por nombre
   */
  export const findProvinciaByNombre = (nombre: string): Provincia | undefined => {
    return PROVINCIAS.find(p => p.nombre.toLowerCase() === nombre.toLowerCase());
  };
  
  /**
   * Buscar localidad por nombre en una provincia
   */
  export const findLocalidadByNombre = (
    provinciaId: string, 
    nombre: string
  ): Localidad | undefined => {
    const localidades = getLocalidadesByProvincia(provinciaId);
    return localidades.find(l => l.nombre.toLowerCase() === nombre.toLowerCase());
  };
  
  /**
   * Obtener todas las localidades (para búsquedas globales)
   */
  export const getAllLocalidades = (): Localidad[] => {
    return Object.values(LOCALIDADES).flat();
  };
  
  /**
   * Buscar localidad por nombre en toda la Argentina
   */
  export const findLocalidadGlobal = (nombre: string): Localidad | undefined => {
    const todasLasLocalidades = getAllLocalidades();
    return todasLasLocalidades.find(l => 
      l.nombre.toLowerCase().includes(nombre.toLowerCase())
    );
  };