// Lista oficial de especialidades médicas
// Usada en: SearchFilters, Register (profesionales)
export const ESPECIALIDADES = [
  'Odontólogo',
  'Ginecólogo',
  'Psicólogo',
  'Traumatólogo',
  'Médico Clínico',
  'Dermatólogo',
  'Oftalmólogo',
  'Otorrino',
  'Pediatra',
  'Cardiólogo',
  'Cirujano General',
  'Gastroenterólogo',
  'Psiquiatra',
  'Urólogo',
  'Endocrinólogo',
  'Neumonólogo',
  'Neurólogo',
  'Kinesiólogo',
  'Nutricionista',
  'Alergista',
  'Fonoaudiólogo',
  'Cirujano Plástico',
  'Médico General y Familiar',
  'Neurocirujano',
  'Psicoanalista',
  'Reumatólogo',
  'Hematólogo',
  'Obstetra',
  'Cirujano Oral y Maxilofacial',
  'Oncólogo',
  'Radiólogo',
  'Infectólogo',
  'Nefrólogo',
  'Patólogo',
  'Analista Clínico',
  'Cirujano Vascular',
  'Neurofisiólogo',
  'Sexólogo',
  'Médico Deportólogo',
  'Cirujano Cardiovascular',
  'Cirujano Digestivo',
  'Psicopedagogo',
  'Homeópata',
  'Geriatra',
  'Cirujano Pediátrico',
  'Flebólogo',
  'Médico Forense',
  'Cirujano Torácico',
  'Osteópata',
  'Médico Laboral',
  'Genetista',
  'Diabetólogo',
  'Hepatólogo',
  'Mastólogo',
  'Terapeuta Complementario',
  'Podólogo',
  'Anestesista',
  'Especialista en Terapia Intensiva',
  'Quiropráctico',
  'Bioquímico',
  'Enfermero',
  'Farmacólogo',
  'Óptico',
  'Psicomotricista',
  'Especialista en Toxicología',
  'Radioterapeuta',
  'Optometría',
  'Protesista - Ortesista'
].sort(); // Ordenadas alfabéticamente
